networks:
  app-tier:
    name: app-tier
    driver: bridge
  monitoring:
    name: monitoring
    driver: bridge    

services:
  tomcat:
    image: tomcat:9.0
    container_name: tomcat
    environment:
      - CATALINA_OPTS=-Xms256m -Xmx512m
        -Dcom.sun.management.jmxremote
        -Dcom.sun.management.jmxremote.port=9090
        -Dcom.sun.management.jmxremote.ssl=false
        -Dcom.sun.management.jmxremote.authenticate=false
        -Djava.rmi.server.hostname=tomcat
        -Dcom.sun.management.jmxremote.rmi.port=9090
    ports:
      - "9081:8081"
      - "9090:9090"
    networks:
      - app-tier
      - monitoring

  jboss:
    image: jboss/wildfly:latest
    container_name: jboss
    environment:
      JAVA_OPTS: > 
        -Xms512m -Xmx1g
        -Dcom.sun.management.jmxremote
        -Dcom.sun.management.jmxremote.port=9091
        -Dcom.sun.management.jmxremote.ssl=false
        -Dcom.sun.management.jmxremote.authenticate=false
        -Djava.rmi.server.hostname=jboss
        -Dcom.sun.management.jmxremote.rmi.port=9091
        -Djava.util.logging.manager=org.jboss.logmanager.LogManager
    ports:
      - "9082:8082"
      - "9091:9091"
    networks:
      - app-tier
      - monitoring
    command: >
      /bin/sh -c "/opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0 -bmanagement 0.0.0.0 &&
      sleep 10 &&
      /opt/jboss/wildfly/bin/jboss-cli.sh --connect --commands='/subsystem=jmx/remoting-connector=jmx:add()'"

  weblogic:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weblogic
    ports:
      - "7001:8083"
      - "9092:9092"
    environment:
      - DOMAIN_NAME=base_domain
      - ADMIN_NAME=AdminServer
      - ADMIN_PORT=7001
      - ADMIN_USERNAME=weblogic
      - ADMIN_PASSWORD=weblogic123
      - ADMINISTRATION_PORT_ENABLED=false
      - PRODUCTION_MODE=dev
      - USER_MEM_ARGS=-Xms512m -Xmx1g
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./domain.properties:/u01/oracle/properties/domain.properties:ro
      - ./jmx.properties:/u01/oracle/properties/jmx.properties:ro
    networks:
      - app-tier
      - monitoring

  websphere:
    image: websphere-liberty:latest
    container_name: websphere
    environment:
      JVM_ARGS: >
        -Xms512m -Xmx1g
        -Dcom.sun.management.jmxremote
        -Dcom.sun.management.jmxremote.port=9096
        -Dcom.sun.management.jmxremote.ssl=false
        -Dcom.sun.management.jmxremote.authenticate=false
        -Djava.rmi.server.hostname=websphere
        -Dcom.sun.management.jmxremote.rmi.port=9096
    ports:
      - "9084:8084"
      - "9096:9096"
    networks:
      - app-tier
      - monitoring
    command: >
      /bin/sh -c "sleep 10 && /opt/ibm/wlp/bin/server start defaultServer &&
      /opt/ibm/wlp/bin/wsadmin.sh -lang jython -f /opt/ibm/wlp/config/configure_jmx.py"

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - monitoring
      - app-tier

  jmx-exporter-tomcat:
    image: bitnami/jmx-exporter:latest
    container_name: jmx-exporter-tomcat
    environment:
      - JMX_HOST=tomcat
      - JMX_PORT=9090
    ports:
      - "1234:1234"
    networks:
      - monitoring
      - app-tier

  jmx-exporter-jboss:
    image: bitnami/jmx-exporter:latest
    container_name: jmx-exporter-jboss
    environment:
      - JMX_HOST=jboss
      - JMX_PORT=9091
    ports:
      - "1235:1235"
    networks:
      - monitoring
      - app-tier

  jmx-exporter-weblogic:
    image: bitnami/jmx-exporter:latest
    container_name: jmx-exporter-weblogic
    environment:
      - JMX_HOST=weblogic
      - JMX_PORT=9092
    ports:
      - "1236:1236"
    networks:
      - monitoring
      - app-tier

  jmx-exporter-websphere:
    image: bitnami/jmx-exporter:latest
    container_name: jmx-exporter-websphere
    environment:
      - JMX_HOST=websphere
      - JMX_PORT=9096
    ports:
      - "1237:1237"
    networks:
      - monitoring
      - app-tier

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9990:8085"
    networks:
      - monitoring
      - app-tier

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9993:9093"
    networks:
      - monitoring
      - app-tier

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:8087"
    volumes:
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - monitoring
      - app-tier

  nginx:
    image: nginx:latest
    container_name: reverse-proxy
    ports:
      - "9080:80"
      - "9443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - monitoring
      - app-tier
