networks:
  monitoring:
    name: monitoring
    driver: bridge
  app-tier:
    external: true

services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - monitoring
      - app-tier

  jmx-exporter-tomcat:
    image: bitnami/jmx-exporter:latest
    container_name: jmx-exporter-tomcat
    environment:
      - JMX_HOST=tomcat
      - JMX_PORT=9090
    ports:
      - "1234:1234"
    networks:
      - monitoring
      - app-tier

  jmx-exporter-jboss:
    image: bitnami/jmx-exporter:latest
    container_name: jmx-exporter-jboss
    environment:
      - JMX_HOST=jboss
      - JMX_PORT=9091
    ports:
      - "1235:1235"
    networks:
      - monitoring
      - app-tier

  jmx-exporter-weblogic:
    image: bitnami/jmx-exporter:latest
    container_name: jmx-exporter-weblogic
    environment:
      - JMX_HOST=weblogic
      - JMX_PORT=9092
    ports:
      - "1236:1236"
    networks:
      - monitoring
      - app-tier

  jmx-exporter-websphere:
    image: bitnami/jmx-exporter:latest
    container_name: jmx-exporter-websphere
    environment:
      - JMX_HOST=websphere
      - JMX_PORT=9093
    ports:
      - "1237:1237"
    networks:
      - monitoring
      - app-tier

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring
      - app-tier

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"
    networks:
      - monitoring
      - app-tier

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - monitoring
      - app-tier
