networks:
  app-tier:
    name: app-tier
    driver: bridge
  monitoring:
    external: true

services:
  tomcat:
    image: tomcat:9.0
    container_name: tomcat
    environment:
      - CATALINA_OPTS=-Xms256m -Xmx512m
        -Dcom.sun.management.jmxremote
        -Dcom.sun.management.jmxremote.port=9090
        -Dcom.sun.management.jmxremote.ssl=false
        -Dcom.sun.management.jmxremote.authenticate=false
        -Djava.rmi.server.hostname=tomcat
        -Dcom.sun.management.jmxremote.rmi.port=9090      
    ports:
      - "8081"
      - "9090:9090"
    networks:
      - app-tier
      - monitoring

  jboss:
    image: jboss/wildfly:latest
    container_name: jboss
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1g
        -Dcom.sun.management.jmxremote
        -Dcom.sun.management.jmxremote.port=9091
        -Dcom.sun.management.jmxremote.ssl=false
        -Dcom.sun.management.jmxremote.authenticate=false
        -Djava.rmi.server.hostname=jboss
        -Dcom.sun.management.jmxremote.rmi.port=9091
        -Djava.util.logging.manager=org.jboss.logmanager.LogManager
    ports:
      - "8082"
      - "9091:9091"
    networks:
      - app-tier
      - monitoring
    command: >
      /bin/sh -c "/opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0 -bmanagement 0.0.0.0 && sleep 10 && /opt/jboss/wildfly/bin/jboss-cli.sh --connect --commands='/subsystem=jmx/remoting-connector=jmx:add()'"

  weblogic:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weblogic
    ports:
      - "8083"
      - "9092:9092"
    environment:
      - DOMAIN_NAME=base_domain
      - ADMIN_NAME=AdminServer
      - ADMIN_PORT=7001
      - ADMIN_USERNAME=weblogic
      - ADMIN_PASSWORD=weblogic123
      - ADMINISTRATION_PORT_ENABLED=false
      - PRODUCTION_MODE=dev
      - USER_MEM_ARGS=-Xms1g -Xmx2g
    volumes:
      - ./domain.properties:/u01/oracle/properties/domain.properties:ro
      - ./jmx.properties:/u01/oracle/properties/jmx.properties:ro
    networks:
      - app-tier
      - monitoring

  websphere:
    image: websphere-liberty:latest
    container_name: websphere
    environment:
      - JVM_ARGS=-Xms512m -Xmx1g
        -Dcom.sun.management.jmxremote
        -Dcom.sun.management.jmxremote.port=9096
        -Dcom.sun.management.jmxremote.ssl=false
        -Dcom.sun.management.jmxremote.authenticate=false
        -Djava.rmi.server.hostname=websphere
        -Dcom.sun.management.jmxremote.rmi.port=9096      
    ports:
      - "8084"
      - "9096:9096"
    networks:
      - app-tier
      - monitoring
    command: >
      /bin/sh -c "sleep 10 && /opt/ibm/wlp/bin/server start defaultServer && /opt/ibm/wlp/bin/wsadmin.sh -lang jython -f /opt/ibm/wlp/config/configure_jmx.py"
