networks:
  app-tier:
    name: app-tier
    driver: bridge
  monitoring:
    external: true

services:
  tomcat:
    image: tomcat:9.0
    container_name: tomcat
    environment:
      - CATALINA_OPTS=-Xms256m -Xmx512m
        -Dcom.sun.management.jmxremote
        -Dcom.sun.management.jmxremote.port=9090
        -Dcom.sun.management.jmxremote.ssl=false
        -Dcom.sun.management.jmxremote.authenticate=false
        -Djava.rmi.server.hostname=tomcat
        -Dcom.sun.management.jmxremote.rmi.port=9090      
    ports:
      - "9081:8080"
      - "9090:9090"
    networks:
      - app-tier
      - monitoring

  jboss:
    image: jboss/wildfly:latest
    container_name: jboss
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1g
        -Dcom.sun.management.jmxremote
        -Dcom.sun.management.jmxremote.port=9091
        -Dcom.sun.management.jmxremote.ssl=false
        -Dcom.sun.management.jmxremote.authenticate=false
        -Djava.rmi.server.hostname=jboss
        -Dcom.sun.management.jmxremote.rmi.port=9091      
    ports:
      - "9082:8080"
      - "9091:9091"
    networks:
      - app-tier
      - monitoring
    command: >
      /bin/sh -c "/opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0 -bmanagement 0.0.0.0 && sleep 10 && /opt/jboss/wildfly/bin/jboss-cli.sh --connect --commands='/subsystem=jmx/remoting-connector=jmx:add()'"

  weblogic:
    image: gstvo2k15/weblogic:12.2.1.4-developer
    container_name: weblogic
    environment:
      - USER_MEM_ARGS=-Xms1g -Xmx2g
    ports:
      - "9083:7001"
    networks:
      - app-tier
      - monitoring
    command: >
      /bin/sh -c "/u01/oracle/startWebLogic.sh && sleep 10 && /u01/oracle/oracle_common/common/bin/wlst.sh /u01/oracle/configure_jmx_weblogic.py"

  websphere:
    image: websphere-liberty:latest
    container_name: websphere
    environment:
      - JVM_ARGS=-Xms512m -Xmx1g
        -Dcom.sun.management.jmxremote
        -Dcom.sun.management.jmxremote.port=9093
        -Dcom.sun.management.jmxremote.ssl=false
        -Dcom.sun.management.jmxremote.authenticate=false
        -Djava.rmi.server.hostname=websphere
        -Dcom.sun.management.jmxremote.rmi.port=9093      
    ports:
      - "9084:9080"
      - "9093:9093"
    networks:
      - app-tier
      - monitoring
    command: >
      /bin/sh -c "sleep 10 && /opt/ibm/wlp/bin/server start defaultServer && /opt/ibm/wlp/bin/wsadmin.sh -lang jython -f /opt/ibm/wlp/config/configure_jmx.py"
